In [1]:
import pandas as pd
from numpy import *
import matplotlib.pyplot as plt
import seaborn as sn

In [2]:
data = pd.read_csv('result_final.csv')
data.head()

,Unnamed: 0,Unnamed: 0.1,link,text,title,date,keywords,summary,title_summary
0,0,0,http://techcrunch.com/2020/09/07/vodafone-idea...,"Vodafone Idea, one of the largest telecom oper...",Indian telecom giant Vodafone Idea rebrands as...,2020-09-07 00:00:00,"['rebrands', 'idea', 'vi', 'giant', 'brand', '...","Vodafone Idea, one of the largest telecom oper...",Indian telecom giant Vodafone Idea rebrands as...
1,1,1,http://techcrunch.com/2020/09/16/facebook-addr...,"At the beginning of the previous decade, Faceb...",Facebook addresses political controversy in In...,2020-09-16 00:00:00,"['opportunities', 'whatsapp', 'controversy', '...",Politicians in the country today heavily rely ...,Facebook addresses political controversy in In...
2,2,2,http://techcrunch.com/2020/09/14/youtube-launc...,"As TikTok’s fate in the U.S. remains murky, Yo...","YouTube launches its TikTok rival, YouTube Sho...",2020-09-14 00:00:00,"['rival', 'video', 'feature', 'access', 'youtu...","As TikTok’s fate in the U.S. remains murky, Yo...","YouTube launches its TikTok rival, YouTube Sho..."
3,3,3,http://techcrunch.com/2020/09/09/groww-an-inve...,Even as more than 150 million people are using...,"Groww, an investment app for millennials in In...",2020-09-09 00:00:00,"['world', 'yc', 'continuity', 'stocks', 'groww...","YC Continuity, the growth-stage investment fun...","Groww, an investment app for millennials in In..."
4,4,4,http://techcrunch.com/2020/09/15/lanzatech-is-...,As part of the continuing global rollout of La...,LanzaTech is developing a small-scale waste bi...,2020-09-15 00:00:00,"['production', 'distributed', 'developing', 's...",As part of the continuing global rollout of La...,LanzaTech is developing a small-scale waste bi...

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2190 entries, 0 to 2189
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     2190 non-null   int64
 1   Unnamed: 0.1   2190 non-null   int64
 2   link           2190 non-null   object
 3   text           2184 non-null   object
 4   title          2187 non-null   object
 5   date           1691 non-null   object
 6   keywords       2187 non-null   object
 7   summary        2184 non-null   object
 8   title_summary  2184 non-null   object
dtypes: int64(2), object(7)
memory usage: 154.1+ KB

In [4]:
data.dtypes

Unnamed: 0        int64
Unnamed: 0.1      int64
link             object
text             object
title            object
date             object
keywords         object
summary          object
title_summary    object
dtype: object

In [5]:
data.isnull().sum()

Unnamed: 0         0
Unnamed: 0.1       0
link               0
text               6
title              3
date             499
keywords           3
summary            6
title_summary      6
dtype: int64

In [6]:
data.dropna(how='any', subset=['title_summary'], inplace=True)
print(data.isnull().sum())

Unnamed: 0         0
Unnamed: 0.1       0
link               0
text               0
title              0
date             495
keywords           0
summary            0
title_summary      0
dtype: int64

In [7]:
for column in data.columns:
  print(f'{column} has {data[data.duplicated(subset=column, keep=False)].shape[0]} duplicate')

Unnamed: 0 has 1792 duplicate
Unnamed: 0.1 has 1792 duplicate
link has 443 duplicate
text has 708 duplicate
title has 782 duplicate
date has 1423 duplicate
keywords has 401 duplicate
summary has 723 duplicate
title_summary has 704 duplicate

In [8]:
#check last and first row of the data frame
def display_data(df,nrows):
    return df.head(nrows).append(df.tail(nrows))

In [9]:
display_data(data[data.duplicated(subset = 'title', keep = False)].sort_values('title'), 4)

,Unnamed: 0,Unnamed: 0.1,link,text,title,date,keywords,summary,title_summary
890,890,890,https://mashable.com/article/contagion-6-month...,All products featured here are independently s...,'Contagion' hits different 6 months into the p...,2020-09-11 18:44:25+00:00,"['pandemic', 'months', 'come', 'contagion', 'j...","In retrospect, I should have realized Contagio...",'Contagion' hits different 6 months into the p...
2051,1151,1151,https://mashable.com/article/contagion-6-month...,All products featured here are independently s...,'Contagion' hits different 6 months into the p...,2020-09-11 18:44:25+00:00,"['hits', 'jory', 'trying', 'days', 'months', '...","In retrospect, I should have realized Contagio...",'Contagion' hits different 6 months into the p...
777,777,777,https://mashable.com/article/princess-bride-re...,There are a whole lot of people who worship th...,'The Princess Bride' cast is reuniting to rais...,2020-09-05 19:04:41+00:00,"['elwes', 'sept', 'virtual', 'thrilled', 'rais...",There are a whole lot of people who worship th...,'The Princess Bride' cast is reuniting to rais...
1181,281,281,https://mashable.com/article/princess-bride-re...,There are a whole lot of people who worship th...,'The Princess Bride' cast is reuniting to rais...,2020-09-05 19:04:41+00:00,"['wisconsin', 'reuniting', 'raise', 'princess'...",There are a whole lot of people who worship th...,'The Princess Bride' cast is reuniting to rais...
1290,390,390,https://mashable.com/article/youtube-announces...,With TikTok’s future in the U.S. up in the air...,YouTube officially announces TikTok competitor...,2020-09-14 18:26:55+00:00,"['competitor', 'announces', 'shorts', 'officia...","On Monday, YouTube officially announced its ne...",YouTube officially announces TikTok competitor...
28,28,28,https://mashable.com/article/youtube-announces...,With TikTok’s future in the U.S. up in the air...,YouTube officially announces TikTok competitor...,2020-09-14 18:26:55+00:00,"['video', 'feature', 'youtube', 'shorts', 'off...","On Monday, YouTube officially announced its ne...",YouTube officially announces TikTok competitor...
358,358,358,https://af.reuters.com/article/commoditiesNews...,《程实专栏》中国“双循环”格局下的内需倍增\n\n“积土成山，风雨兴焉。”面向中国经济的高质...,路透中文网,NaN,"['路透中文网', '程实专栏中国双循环格局下的内需倍增积土成山风雨兴焉面向中国经济的高质量...",《程实专栏》中国“双循环”格局下的内需倍增“积土成山，风雨兴焉。”面向中国经济的高质量发展，...,路透中文网 《程实专栏》中国“双循环”格局下的内需倍增\n\n“积土成山，风雨兴焉。”面向中...
74,74,74,https://af.reuters.com/article/uk-health-coron...,《程实专栏》中国“双循环”格局下的内需倍增\n\n“积土成山，风雨兴焉。”面向中国经济的高质...,路透中文网,NaN,"['路透中文网', '程实专栏中国双循环格局下的内需倍增积土成山风雨兴焉面向中国经济的高质量...",《程实专栏》中国“双循环”格局下的内需倍增“积土成山，风雨兴焉。”面向中国经济的高质量发展，...,路透中文网 《程实专栏》中国“双循环”格局下的内需倍增\n\n“积土成山，风雨兴焉。”面向中...

In [10]:
data.drop_duplicates(subset='title', keep='first', inplace=True)
print(data.shape)

(1720, 9)

In [11]:
for column in data.columns:
    print(f' {column} has {data[data.duplicated(subset = column, keep = False)].shape[0]} duplicates')

 Unnamed: 0 has 1176 duplicates
 Unnamed: 0.1 has 1176 duplicates
 link has 0 duplicates
 text has 6 duplicates
 title has 0 duplicates
 date has 982 duplicates
 keywords has 2 duplicates
 summary has 12 duplicates
 title_summary has 0 duplicates

In [12]:
data[data.duplicated(subset = 'text')]

,Unnamed: 0,Unnamed: 0.1,link,text,title,date,keywords,summary,title_summary
125,125,125,https://www.nytimes.com/2020/08/19/us/politics...,"“Hey, everybody, it’s me, Kamala.” “Tonight we...","Kamala Harris Takes the Spotlight, a Moment fo...",2020-08-19 00:00:00,"['world', 'women', 'democratic', 'woman', 'har...","Our worst impulses unleashed, our proud reputa...","Kamala Harris Takes the Spotlight, a Moment fo..."
337,337,337,https://in.reuters.com/news/picture/chadwick-b...,"More than 12,000 people, mostly refugees from ...",Chadwick Boseman: 1976 - 2020,2020-08-29 17:11:11+00:00,"['syria', 'shelter', 'moria', 'chadwick', 'ope...","More than 12,000 people, mostly refugees from ...","Chadwick Boseman: 1976 - 2020 More than 12,000..."
2136,1236,1236,https://www.reuters.com/article/us-germany-eco...,BERLIN (Reuters) - Europe’s largest economy is...,"German economic recovery to continue in H2, Q3...",2020-09-15 21:17:01+00:00,"['ministry', 'quarter', 'second', 'h2', 'econo...","“The German economy is continuing to pick up, ...","German economic recovery to continue in H2, Q3..."

In [13]:
data.drop_duplicates(subset = 'text', keep = 'first', inplace = True)

In [14]:
def create_soup(x):
    return x['title'] + ' ' + x['keywords'] + ' ' + x['summary'] + ' ' + x['text']
data['soup'] = data.apply(create_soup, axis=1)

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidv = TfidfVectorizer(strip_accents = 'ascii', stop_words = 'english')
tfidfv_matrix = tfidv.fit_transform(data['soup'])
features = pd.DataFrame(tfidfv_matrix.toarray(), columns=tfidv.get_feature_names(), index = data['title'])
features.head()

,00,000,0000,000and,000ft,000km,000mah,000s,000sq,000th,...,zuoyebang,zurich,zverev,zverevs,zwickau,zwicker,zwicky,zwift,zwifts,zynga
title,,,,,,,,,,,,,,,,,,,,,
Indian telecom giant Vodafone Idea rebrands as ‘Vi’ – TechCrunch,0.0,0.011613,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Facebook addresses political controversy in India, monetization opportunities, startup investments – TechCrunch",0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"YouTube launches its TikTok rival, YouTube Shorts, initially in India – TechCrunch",0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Groww, an investment app for millennials in India, raises $30M led by YC Continuity – TechCrunch",0.0,0.014196,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LanzaTech is developing a small-scale waste biomass gasifier for ethanol production in India – TechCrunch,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
from sklearn.decomposition import NMF

nmf = NMF(n_components=20)
topics = nmf.fit_transform(features)

/opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages/sklearn/decomposition/_nmf.py:312: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  warnings.warn(("The 'init' value, when 'init=None' and "

In [17]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(topics, topics)
indices = pd.Series(data.index, index = data['title']).drop_duplicates()


def get_recommendations(title, no_of_news_article):

    idx = indices[title]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:no_of_news_article+1]
    
    print("Article Read -- " + data['title'].iloc[idx] +" link --"+ data['link'].iloc[idx])
    print(" ---------------------------------------------------------- ")
    
    news_indices = [i[0] for i in sim_scores]
    
    for i in range(len(news_indices)):
        print("Recomendation "+ str(i+1)+" --- " +str(news_indices[i])+"(IDX)  "+str(data['date'].iloc[news_indices[i]])+" : "+
              data['title'].iloc[news_indices[i]] +" || Link --"+ data['link'].iloc[news_indices[i]] +" score -- "+ str(sim_scores[i][1]))
        print()

In [18]:
get_recommendations('Oracle boots out Microsoft and wins bid for TikTok, reports say – TechCrunch', 5)

Article Read -- Oracle boots out Microsoft and wins bid for TikTok, reports say – TechCrunch link --http://techcrunch.com/2020/09/13/oracle-wins-bid-to-buy-tiktok/
 ----------------------------------------------------------
Recomendation 1 --- 473(IDX)  2020-08-27 00:00:00 : Walmart expresses interest in TikTok, teaming up with Microsoft – TechCrunch || Link --http://techcrunch.com/2020/08/27/tiktok-deal/ score -- 0.07477054328199888

Recomendation 2 --- 10(IDX)  2020-09-13 00:00:00 : Oracle boots out Microsoft and wins bid for TikTok, reports say – TechCrunch || Link --http://techcrunch.com/2020/09/13/oracle-wins-bid-to-buy-tiktok/ score -- 0.07423411800871305

Recomendation 3 --- 1198(IDX)  2020-08-24 06:03:30+00:00 : Exclusive: ByteDance investors seek to use stakes to finance TikTok bid || Link --https://www.reuters.com/article/us-usa-tiktok-bytedance-investors-exclus-idUSKBN25K0IW score -- 0.07383529245746161

Recomendation 4 --- 1297(IDX)  2020-08-30 04:33:18+00:00 : China's new tech export controls could give Beijing a say in TikTok sale || Link --https://in.reuters.com/article/us-usa-tiktok-china-idINKBN25Q05Q score -- 0.07020965296392091

Recomendation 5 --- 1322(IDX)  nan : How TikTok got caught in the middle of a trade war with China || Link --https://www.engadget.com/how-tiktok-got-caught-in-middle-trade-war-with-china-223010428.html score -- 0.06457451356006248